version: '2'

services:
  openresty:
    image: openresty/openresty
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf/vhost:/usr/local/openresty/nginx/conf/vhost
      - ./logs:/usr/local/openresty/nginx/logs
      - ./conf/proxy_ip:/proxy_ip
    ports:
      - 8888:80