openresty:
  image: openresty-php
  volumes:
    - /docker/openresty/conf:/usr/local/openresty/nginx/conf
    - /srv/docker/openresty/logs:/usr/local/openresty/nginx/logs
    - /www:/www
  ports:
    - "80:80"
